- name: manage packages on windows
  hosts: all
  vars:
    action_triggered: null 
    msi_arguments: ["/quiet"] 
    # multiple arguments have to be defined as list ex.: ["item1","item2"]
  tasks:

    - name: "uninstall package {{ windows_package_path }}"
      win_package:
        path: "{{ windows_package_path }}"
        arguments: "{{ msi_arguments }}"
      when: ( windows_package_path is defined and action_triggered == "uninstall" ) or
        ( windows_package_path is defined and action_triggered == "reinstall" )

    - name: "install package {{ windows_package_path }}"
      win_package:
        path: "{{ windows_package_path }}"
        arguments: "{{ msi_arguments }}"
        state: present
      when: ( windows_package_path is defined and action_triggered == "install" ) or
        ( windows_package_path is defined and action_triggered == "reinstall" )
